In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [22]:
import plotly as py
import plotly.express as px
import plotly.graph_objs as go
from plotly.offline import iplot, init_notebook_mode
#init_notebook_mode(connected=True)

import cufflinks as cf
cf.go_offline(connected=True)
cf.set_config_file(colorscale='plotly', world_readable=True)

# Extra options
# pd.options.display.max_rows = 30
# pd.options.display.max_columns = 25

# Show all code cells outputs
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

import os
from IPython.display import Image, display, HTML

In [23]:
import ipywidgets as widgets
from ipywidgets import interact, interact_manual

In [2]:
# store login data in login.py
%run login.py

In [3]:
# login query as multiline formatted string
# this assumes that login and pwd are defined 
# above

loginquery = f"""
mutation {{
  logIn(
      email:\"{login}\",
      password:\"{pwd}\") {{
    jwt {{
      token
      exp
    }}
  }}
}}
"""

In [4]:
import requests
url = 'https://api.numina.co/graphql'

mylogin = requests.post(url, json={'query': loginquery})
mylogin

In [5]:
token = mylogin.json()['data']['logIn']['jwt']['token']

In [6]:
expdate = mylogin.json()
expdate

{'data': {'logIn': {'jwt': {'exp': '2020-03-19T18:49:55.788762',
    'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1ODQ2NDM3OTUsImlhdCI6MTU4NDU1NzM5NSwic3ViIjoyNzd9.lPVEYRx8bjdioxegCJpxGI6n-ivcHGpO1rKHPRHR-68'}}}}

### 307 requires maintenance after 500 visitors or 500 hours of use, when should 307 plan on scheduling maintenance operations (e.g., what days and times)?

In [7]:
device_ids = ['SWLSANDBOX1', 'SWLSANDBOX2', 'SWLSANDBOX3']

In [8]:
def get_dwell(func, ID):
    '''
    func is either feedDwellTimeDistribution or zoneDwellTimeDistribution
    '''
    if func == 'feedDwellTimeDistribution':
        arg = 'serialnos: "{0}"'.format(ID)
    else:
        arg = 'zoneIds: {0}'.format(ID)
        
    query = """
    query {{
        {0}(
        {1},
        startTime: "2019-02-20T00:00:00",
        endTime: "2020-01-12T00:00:00",
        timezone: "America/New_York",
        objClasses: ["pedestrian"],
        interval: "1h"
        ){{
        edges {{
          node {{
            time
            objClass
            pct100
            pct75
            pct50
            pct25
            mean
            count
          }}
        }}
      }}
    }}
    """.format(func, arg)

    dwell = requests.post(url, json={'query': query}, 
                           headers = {'Authorization':token})
    
    df = pd.DataFrame([x['node'] for x in dwell.json()['data'][func]['edges']])
    if func == 'feedDwellTimeDistribution':
        df['device'] = ID
    else:
        df['zone'] = ID
    
    return df

In [9]:
feed_dwell_df = pd.concat([get_dwell('feedDwellTimeDistribution', device_ids[i]) 
                           for i in range(3)])

In [15]:
nonzero_df = feed_dwell_df[feed_dwell_df['count']!=0]

In [16]:
nonzero_df

,count,mean,objClass,pct100,pct25,pct50,pct75,time,device
9,18,21.80,pedestrian,47.44,2.61,2.61,7.23,2019-02-20T09:00:00-05:00,SWLSANDBOX1
10,200,8.38,pedestrian,9.91,2.09,2.09,4.19,2019-02-20T10:00:00-05:00,SWLSANDBOX1
11,291,9.05,pedestrian,11.47,2.11,2.11,4.72,2019-02-20T11:00:00-05:00,SWLSANDBOX1
12,716,20.25,pedestrian,18.23,2.63,2.63,6.73,2019-02-20T12:00:00-05:00,SWLSANDBOX1
13,520,13.82,pedestrian,15.08,2.61,2.61,5.78,2019-02-20T13:00:00-05:00,SWLSANDBOX1
...,...,...,...,...,...,...,...,...,...
7800,1,1.04,pedestrian,1.04,1.04,1.04,1.04,2020-01-11T00:00:00-05:00,SWLSANDBOX3
7814,5,4.77,pedestrian,6.26,3.58,3.58,5.22,2020-01-11T14:00:00-05:00,SWLSANDBOX3
7816,3,19.05,pedestrian,38.46,6.21,6.21,12.48,2020-01-11T16:00:00-05:00,SWLSANDBOX3
7817,13,17.69,pedestrian,26.04,5.22,5.22,11.97,2020-01-11T17:00:00-05:00,SWLSANDBOX3
7818,1,3.69,pedestrian,3.69,3.69,3.69,3.69,2020-01-11T18:00:00-05:00,SWLSANDBOX3

In [17]:
# replace NaN with 0
nonzero_df = nonzero_df.fillna(0)

In [18]:
nonzero_df['time'] = nonzero_df['time'].str[:-6].apply(lambda x : pd.Timestamp(x))

In [19]:
nonzero_df

,count,mean,objClass,pct100,pct25,pct50,pct75,time,device
9,18,21.80,pedestrian,47.44,2.61,2.61,7.23,2019-02-20 09:00:00,SWLSANDBOX1
10,200,8.38,pedestrian,9.91,2.09,2.09,4.19,2019-02-20 10:00:00,SWLSANDBOX1
11,291,9.05,pedestrian,11.47,2.11,2.11,4.72,2019-02-20 11:00:00,SWLSANDBOX1
12,716,20.25,pedestrian,18.23,2.63,2.63,6.73,2019-02-20 12:00:00,SWLSANDBOX1
13,520,13.82,pedestrian,15.08,2.61,2.61,5.78,2019-02-20 13:00:00,SWLSANDBOX1
...,...,...,...,...,...,...,...,...,...
7800,1,1.04,pedestrian,1.04,1.04,1.04,1.04,2020-01-11 00:00:00,SWLSANDBOX3
7814,5,4.77,pedestrian,6.26,3.58,3.58,5.22,2020-01-11 14:00:00,SWLSANDBOX3
7816,3,19.05,pedestrian,38.46,6.21,6.21,12.48,2020-01-11 16:00:00,SWLSANDBOX3
7817,13,17.69,pedestrian,26.04,5.22,5.22,11.97,2020-01-11 17:00:00,SWLSANDBOX3
7818,1,3.69,pedestrian,3.69,3.69,3.69,3.69,2020-01-11 18:00:00,SWLSANDBOX3

In [30]:
def plot_count(selected, start_date, end_date):
    '''
    device_or_zone is either 'device' or 'zone';
    selected is a list of device rawIds or zone rawIds;
    metric is a value in ['mean', 'pct100', 'pct75', 'pct50', 'pct25']
    '''
    df = nonzero_df
        
    plot_df = df.loc[(df.time.dt.date >= start_date) & 
                     (df.time.dt.date <= end_date)].copy()
    
    fig = go.Figure()
    
    for device in selected:
        sub_df = plot_df[plot_df['device'] == device]
        fig.add_trace(go.Scatter(x=sub_df.time, y=sub_df['count'], mode='lines', name=device))
    
    fig.update_layout(
        title="Pedestrian count grouped by device",
        xaxis_title="time",
        yaxis_title="device")
    
    fig.show()

In [31]:
# SWLSANDBOX1 = Streetscape
# SWLSANDBOX2 = Under Raincoat
# SWLSANDBOX3 = Outside
_ = interact(plot_count, 
             selected=widgets.SelectMultiple(options=device_ids, value=device_ids, disabled=False),
             start_date=widgets.DatePicker(value=pd.to_datetime('2019-02-20')),
             end_date=widgets.DatePicker(value=pd.to_datetime('2020-01-12')),
            )

interactive(children=(SelectMultiple(description='selected', index=(0, 1, 2), options=('SWLSANDBOX1', 'SWLSAND…

### Observations
-sandbox1 has higher count on average than the other two  
-sandbox3 is outside--can consider weather data  
-peak calling?